# Generated by Django 6.0.5 on 2026-05-26 06:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calle',
            fields=[
                ('idcalle', models.AutoField(primary_key=True, serialize=False)),
                ('calle', models.CharField(max_length=200)),
                ('ciudad', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'calles',
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('idciudad', models.AutoField(primary_key=True, serialize=False)),
                ('ciudad', models.CharField(max_length=100)),
                ('condado', models.CharField(blank=True, max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ciudades',
            },
        ),
        migrations.CreateModel(
            name='Condado',
            fields=[
                ('idcondado', models.AutoField(primary_key=True, serialize=False)),
                ('condado', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'condados',
            },
        ),
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('idconductor', models.AutoField(primary_key=True, serialize=False)),
                ('apellidos', models.CharField(max_length=100)),
                ('nombres', models.CharField(max_length=100)),
                ('identificacion', models.CharField(max_length=20, unique=True)),
                ('genero', models.CharField(max_length=1)),
                ('tipolicencia', models.CharField(max_length=10)),
                ('estadolicencia', models.CharField(max_length=20)),
                ('ciudadresidencia', models.CharField(max_length=100)),
                ('aniosexperiencia', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'conductores',
            },
        ),
        migrations.CreateModel(
            name='ElementoFisico',
            fields=[
                ('idelementofisico', models.AutoField(primary_key=True, serialize=False)),
                ('cercacruce', models.BooleanField(default=False)),
                ('cercasemaforo', models.BooleanField(default=False)),
                ('cercaparada', models.BooleanField(default=False)),
                ('cercaestacion', models.BooleanField(default=False)),
                ('cercabache', models.BooleanField(default=False)),
                ('cercaviatren', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'elementosfisicos',
            },
        ),
        migrations.CreateModel(
            name='EstadoClima',
            fields=[
                ('idestadoclima', models.AutoField(primary_key=True, serialize=False)),
                ('direccionviento', models.CharField(blank=True, max_length=50)),
                ('condicionclima', models.CharField(max_length=100)),
                ('temperaturaf', models.FloatField(blank=True, null=True)),
                ('sensaciontermicaf', models.FloatField(blank=True, null=True)),
                ('humedadporcentaje', models.FloatField(blank=True, null=True)),
                ('presionpulgadas', models.FloatField(blank=True, null=True)),
                ('visibilidadmillas', models.FloatField(blank=True, null=True)),
                ('velocidadvientomph', models.FloatField(blank=True, null=True)),
                ('precipitacionpulgadas', models.FloatField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'estadoclima',
            },
        ),
        migrations.CreateModel(
            name='EstadoConductor',
            fields=[
                ('idestadoconductor', models.AutoField(primary_key=True, serialize=False)),
                ('estadosobriedad', models.BooleanField(default=True)),
                ('nivelatencion', models.BooleanField(default=True)),
                ('condicionfisica', models.BooleanField(default=True)),
                ('usoseguridad', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'estadosconductores',
            },
        ),
        migrations.CreateModel(
            name='EstadoGeografico',
            fields=[
                ('idestado', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'estados',
            },
        ),
        migrations.CreateModel(
            name='Fecha',
            fields=[
                ('idfecha', models.AutoField(primary_key=True, serialize=False)),
                ('fechacompleta', models.CharField(max_length=20)),
                ('anio', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('dia', models.IntegerField()),
                ('trimestre', models.IntegerField()),
                ('semanaanio', models.IntegerField()),
                ('diasemana', models.CharField(max_length=20)),
                ('esfinsemana', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fechas',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('idpais', models.AutoField(primary_key=True, serialize=False)),
                ('pais', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'paises',
            },
        ),
        migrations.CreateModel(
            name='PeriodoDia',
            fields=[
                ('idperiododia', models.AutoField(primary_key=True, serialize=False)),
                ('amaneceranochecer', models.CharField(max_length=50)),
                ('crepusculocivil', models.CharField(max_length=50)),
                ('crepusculonautico', models.CharField(max_length=50)),
                ('crepusculoastronomico', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'periodosdias',
            },
        ),
        migrations.CreateModel(
            name='ReferenciaEstacion',
            fields=[
                ('idreferenciaestacion', models.AutoField(primary_key=True, serialize=False)),
                ('codigoaeropuerto', models.CharField(max_length=20)),
                ('zonahoraria', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'referenciaestacion',
            },
        ),
        migrations.CreateModel(
            name='Severidad',
            fields=[
                ('idseveridad', models.AutoField(primary_key=True, serialize=False)),
                ('severidad', models.IntegerField()),
                ('descripcion', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'severidades',
            },
        ),
        migrations.CreateModel(
            name='TipoEstadoIncidente',
            fields=[
                ('idtipoestadoincidente', models.AutoField(primary_key=True, serialize=False)),
                ('tipoestadoincidente', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tiposestadosincidentes',
            },
        ),
        migrations.CreateModel(
            name='TipoReportado',
            fields=[
                ('idtiporeportado', models.AutoField(primary_key=True, serialize=False)),
                ('tiporeportado', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tiposreportados',
            },
        ),
        migrations.CreateModel(
            name='UnidadEmergencia',
            fields=[
                ('idunidademergencia', models.AutoField(primary_key=True, serialize=False)),
                ('unidademergencia', models.CharField(max_length=100)),
                ('tipounidademergencia', models.CharField(choices=[('AMBULANCIA', 'Ambulancia'), ('POLICIA', 'Policía'), ('GRUA', 'Grúa'), ('BOMBEROS', 'Bomberos')], max_length=20)),
                ('estadounidad', models.CharField(choices=[('EN_BASE', 'En Base'), ('EN_CAMINO', 'En Camino'), ('EN_ESCENA', 'En Escena'), ('EN_TRASLADO', 'En Traslado'), ('REGRESO', 'Regreso'), ('DISPONIBLE', 'Disponible')], default='EN_BASE', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Unidad de Emergencia',
                'db_table': 'unidadesemergencia',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.AutoField(primary_key=True, serialize=False)),
                ('apellidos', models.CharField(max_length=100)),
                ('nombres', models.CharField(max_length=100)),
                ('gmail', models.EmailField(max_length=254, unique=True)),
                ('identificacion', models.CharField(max_length=20, unique=True)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1)),
                ('fechanacimiento', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('idvehiculo', models.AutoField(primary_key=True, serialize=False)),
                ('tipovehiculo', models.CharField(max_length=50)),
                ('modelovehiculo', models.CharField(max_length=100)),
                ('categoriausovehiculo', models.CharField(max_length=50)),
                ('mercanciapeligrosa', models.BooleanField(default=False)),
                ('ejes', models.IntegerField(default=2)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'vehiculos',
            },
        ),
        migrations.CreateModel(
            name='Accidente',
            fields=[
                ('idaccidente', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('horainicio', models.TimeField()),
                ('horafin', models.TimeField(blank=True, null=True)),
                ('descripcion', models.TextField()),
                ('codigopostal', models.CharField(blank=True, max_length=10)),
                ('activo', models.BooleanField(default=True)),
                ('duracionminutos', models.IntegerField(blank=True, null=True)),
                ('numvehiculos', models.PositiveIntegerField(default=1)),
                ('numvictimas', models.PositiveIntegerField(default=0)),
                ('numheridos', models.PositiveIntegerField(default=0)),
                ('numfallecidos', models.PositiveIntegerField(default=0)),
                ('latitudinicio', models.DecimalField(decimal_places=8, max_digits=12)),
                ('longitudinicio', models.DecimalField(decimal_places=8, max_digits=12)),
                ('distanciamillas', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('fechahoraclima', models.DateTimeField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('idcalle', models.ForeignKey(db_column='idcalle', on_delete=django.db.models.deletion.PROTECT, to='accidentes.calle')),
                ('idciudad', models.ForeignKey(db_column='idciudad', on_delete=django.db.models.deletion.PROTECT, to='accidentes.ciudad')),
                ('idcondado', models.ForeignKey(blank=True, db_column='idcondado', null=True, on_delete=django.db.models.deletion.PROTECT, to='accidentes.condado')),
                ('idelementofisico', models.ForeignKey(blank=True, db_column='idelementofisico', null=True, on_delete=django.db.models.deletion.PROTECT, to='accidentes.elementofisico')),
                ('idestadoclima', models.ForeignKey(blank=True, db_column='idestadoclima', null=True, on_delete=django.db.models.deletion.PROTECT, to='accidentes.estadoclima')),
                ('idestado', models.ForeignKey(blank=True, db_column='idestado', null=True, on_delete=django.db.models.deletion.PROTECT, to='accidentes.estadogeografico')),
                ('idfecha', models.ForeignKey(blank=True, db_column='idfecha', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accidentes.fecha')),
                ('idpais', models.ForeignKey(blank=True, db_column='idpais', null=True, on_delete=django.db.models.deletion.PROTECT, to='accidentes.pais')),
                ('idperiododia', models.ForeignKey(blank=True, db_column='idperiododia', null=True, on_delete=django.db.models.deletion.PROTECT, to='accidentes.periododia')),
                ('idreferenciaestacion', models.ForeignKey(blank=True, db_column='idreferenciaestacion', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accidentes.referenciaestacion')),
                ('idseveridad', models.ForeignKey(db_column='idseveridad', on_delete=django.db.models.deletion.PROTECT, to='accidentes.severidad')),
                ('idtiporeportado', models.ForeignKey(db_column='idtiporeportado', on_delete=django.db.models.deletion.PROTECT, to='accidentes.tiporeportado')),
                ('idusuario', models.ForeignKey(db_column='idusuario', on_delete=django.db.models.deletion.PROTECT, to='accidentes.usuario')),
            ],
            options={
                'db_table': 'accidentes',
                'ordering': ['-fecha_actualizacion'],
            },
        ),
        migrations.CreateModel(
            name='EvidenciaFoto',
            fields=[
                ('idevidenciafoto', models.AutoField(primary_key=True, serialize=False)),
                ('urlevidenciafoto', models.URLField(max_length=500)),
                ('fechahora', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('idaccidente', models.ForeignKey(db_column='idaccidente', on_delete=django.db.models.deletion.CASCADE, to='accidentes.accidente')),
            ],
            options={
                'db_table': 'evidenciasfotos',
            },
        ),
        migrations.CreateModel(
            name='Implicado',
            fields=[
                ('idimplicado', models.AutoField(primary_key=True, serialize=False)),
                ('tipoimplicado', models.CharField(choices=[('CONDUCTOR', 'Conductor'), ('PASAJERO', 'Pasajero'), ('PEATON', 'Peatón'), ('OTRO', 'Otro')], max_length=20)),
                ('genero', models.CharField(max_length=1)),
                ('estadoimplicado', models.CharField(choices=[('ILESO', 'Ileso'), ('HERIDO_LEVE', 'Herido Leve'), ('HERIDO_GRAVE', 'Herido Grave'), ('FALLECIDO', 'Fallecido')], max_length=20)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('idaccidente', models.ForeignKey(db_column='idaccidente', on_delete=django.db.models.deletion.CASCADE, to='accidentes.accidente')),
            ],
            options={
                'db_table': 'implicados',
            },
        ),
        migrations.CreateModel(
            name='AccidenteTipoEstadoIncidente',
            fields=[
                ('idaccidentetipoestadoincidente', models.AutoField(primary_key=True, serialize=False)),
                ('fechahoramodificado', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('idaccidente', models.ForeignKey(db_column='idaccidente', on_delete=django.db.models.deletion.CASCADE, to='accidentes.accidente')),
                ('idtipoestadoincidente', models.ForeignKey(db_column='idtipoestadoincidente', on_delete=django.db.models.deletion.PROTECT, to='accidentes.tipoestadoincidente')),
            ],
            options={
                'db_table': 'accidentestiposestadosincidentes',
                'ordering': ['-fechahoramodificado'],
            },
        ),
        migrations.CreateModel(
            name='Despacho',
            fields=[
                ('iddespacho', models.AutoField(primary_key=True, serialize=False)),
                ('fechahoradespacho', models.DateTimeField(auto_now_add=True)),
                ('fechahoraconfirmacion', models.DateTimeField(blank=True, null=True)),
                ('fechahorallegada', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('idaccidente', models.ForeignKey(db_column='idaccidente', on_delete=django.db.models.deletion.CASCADE, to='accidentes.accidente')),
                ('idunidademergencia', models.ForeignKey(db_column='idunidademergencia', on_delete=django.db.models.deletion.PROTECT, to='accidentes.unidademergencia')),
            ],
            options={
                'db_table': 'despachos',
            },
        ),
        migrations.CreateModel(
            name='NotaAccidente',
            fields=[
                ('idnotaaccidentes', models.AutoField(primary_key=True, serialize=False)),
                ('nota', models.TextField()),
                ('tipo', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now_add=True)),
                ('idaccidente', models.ForeignKey(db_column='idaccidente', on_delete=django.db.models.deletion.CASCADE, to='accidentes.accidente')),
                ('idusuario', models.ForeignKey(db_column='idusuario', on_delete=django.db.models.deletion.PROTECT, to='accidentes.usuario')),
            ],
            options={
                'db_table': 'notasaccidentes',
                'ordering': ['-fecha_actualizacion'],
            },
        ),
        migrations.CreateModel(
            name='ConductorAccidente',
            fields=[
                ('idconductoraccidente', models.AutoField(primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('idaccidente', models.ForeignKey(db_column='idaccidente', on_delete=django.db.models.deletion.CASCADE, to='accidentes.accidente')),
                ('idconductor', models.ForeignKey(db_column='idconductor', on_delete=django.db.models.deletion.PROTECT, to='accidentes.conductor')),
                ('idestadoconductor', models.ForeignKey(db_column='idestadoconductor', on_delete=django.db.models.deletion.PROTECT, to='accidentes.estadoconductor')),
                ('idvehiculo', models.ForeignKey(db_column='idvehiculo', on_delete=django.db.models.deletion.PROTECT, to='accidentes.vehiculo')),
            ],
            options={
                'db_table': 'conductoresaccidentes',
            },
        ),
        migrations.AddIndex(
            model_name='accidente',
            index=models.Index(fields=['activo', 'fecha_actualizacion'], name='accidentes_activo_a0c81e_idx'),
        ),
        migrations.AddIndex(
            model_name='accidente',
            index=models.Index(fields=['latitudinicio', 'longitudinicio'], name='accidentes_latitud_3322f7_idx'),
        ),
    ]
